on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  update-semver:
    permissions:
      contents: write
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.GH_TOKEN_ADMIN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - uses: ./
